import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, Cell, Pie, PieChart, Tooltip, XAxis, YAxis } from 'recharts'
import { useQuery } from '@tanstack/react-query'
import { TopBar } from '@/components/layout/TopBar'
import { ChartContainer, chartTooltipStyle } from '@/components/charts/ChartContainer'
import { ErrorState } from '@/components/feedback/ErrorState'
import { LoadingState } from '@/components/feedback/LoadingState'
import { StatusBadge } from '@/components/ui/status-badge'
import { ObservabilityCard, ObservabilityHero, Metric } from '@/features/observability/components'
import { useValidationResults } from '@/features/quality/hooks/useValidationResults'
import { getQualityHistory, getQualitySummary } from '@/services/qualityApi'
import { formatAbsoluteTime, formatNumber } from '@/lib/formatters'
import type { GXValidation } from '@/types/quality'

const DATASETS = ['customers', 'orders', 'products', 'payments', 'api_customers', 'api_orders', 'api_products']
const CHECKS = ['Null checks', 'Uniqueness', 'Volume checks', 'Referential integrity', 'Positive values']
const PIE_COLORS = ['#DC2626', '#7F1D1D', '#F97316', '#FB7185', '#B91C1C', '#D97706']
const displayDataset = (value: string) => value.replace(/_/g, ' ')
function checkGroup(expectation: string) { const value = expectation.toLowerCase(); if (value.includes('not_be_null')) return 'Null checks'; if (value.includes('unique')) return 'Uniqueness'; if (value.includes('row_count')) return 'Volume checks'; if (value.includes('in_set')) return 'Referential integrity'; return 'Positive values' }

export function DataQualityCenterPage() {
  const validations = useValidationResults()
  const summary = useQuery({ queryKey: ['quality', 'summary'], queryFn: getQualitySummary })
  const history = useQuery({ queryKey: ['quality', 'history'], queryFn: getQualityHistory })
  const [selected, setSelected] = useState<GXValidation | null>(null)
  const records = validations.data?.validations ?? []
  const failures = records.filter(record => record.status === 'failed')
  const runs = (history.data?.executions ?? []).slice(-12).reverse()
  const distribution = [{ name: 'Passed', value: summary.data?.passed ?? 0 }, { name: 'Failed', value: summary.data?.failed ?? 0 }]
  const failureDistribution = history.data?.failureDistribution ?? []

  return <div className="flex min-h-screen min-w-0 flex-col"><TopBar title="Data Quality Center" description="Great Expectations health, failures, and execution observability" /><main className="flex-1 space-y-6 p-6 pb-6">
    <ObservabilityHero eyebrow="Data observability" title="Trust signals across every warehouse dataset." description="Validation coverage, execution trends, and actionable expectation failures in one view." status={summary.data?.lastValidationRun ? `Last run ${formatAbsoluteTime(summary.data.lastValidationRun)}` : 'Waiting for validation run'} />
    <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Validation success" value={`${summary.data?.successRate ?? 0}%`} detail="Across completed GX executions" /><Metric label="Passed expectations" value={formatNumber(summary.data?.passed ?? 0)} detail="Persisted historical results" /><Metric label="Failed expectations" value={formatNumber(summary.data?.failed ?? 0)} detail="Grouped by failed expectation" /><Metric label="Total coverage" value={formatNumber(summary.data?.totalExpectations ?? 0)} detail="All completed executions" /></section>
    {(validations.isLoading || history.isLoading) && <LoadingState variant="chart" />}
    {(validations.isError || history.isError) && <ErrorState onRetry={() => { validations.refetch(); history.refetch() }} />}
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.4fr_0.6fr]"><ObservabilityCard title="Validation health trend" description="One success-rate point per persisted Great Expectations execution.">{history.data && <ChartContainer isEmpty={!history.data.trend.length}><AreaChart data={history.data.trend}><defs><linearGradient id="qualityArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#EF4444" stopOpacity={0.48} /><stop offset="100%" stopColor="#7F1D1D" stopOpacity={0.03} /></linearGradient></defs><XAxis dataKey="timestamp" tickFormatter={value => new Date(value).toLocaleDateString()} tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip {...chartTooltipStyle} /><Area type="monotone" dataKey="successRate" name="Success rate %" stroke="#EF4444" strokeWidth={3} fill="url(#qualityArea)" /></AreaChart></ChartContainer>}</ObservabilityCard><ObservabilityCard title="Failure distribution" description="Failed expectation types across retained execution history."><ChartContainer isEmpty={!failureDistribution.length}><PieChart><Pie data={failureDistribution} dataKey="count" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={3}>{failureDistribution.map((item, index) => <Cell key={item.name} fill={PIE_COLORS[index % PIE_COLORS.length]} />)}</Pie><Tooltip {...chartTooltipStyle} /></PieChart></ChartContainer><div className="mt-2 flex flex-wrap justify-center gap-x-4 gap-y-2 text-xs text-[var(--color-text-secondary)]">{failureDistribution.slice(0, 4).map((item, index) => <span key={item.name} className="flex items-center gap-2"><i className="h-2 w-2 rounded-full" style={{ background: PIE_COLORS[index % PIE_COLORS.length] }} />{item.name}: {formatNumber(item.count)}</span>)}</div></ObservabilityCard></div>
    <ObservabilityCard title="Data quality validation network" description="Dataset → validation family → latest expectation outcome. Select a node for details."><div className="space-y-4">{DATASETS.map(dataset => { const datasetRecords = records.filter(record => record.dataset.toLowerCase().replace(/\s/g, '_') === dataset); return <div key={dataset} className="flex flex-wrap items-center gap-2 rounded-lg border border-red-950/50 bg-[#180f10] p-3"><Link to={`/quality/${dataset.replace('api_', '')}`} className="rounded-md border border-red-800 bg-red-950/50 px-3 py-2 text-sm font-semibold capitalize text-red-100 hover:bg-red-900/60">{displayDataset(dataset)}</Link><span className="text-red-500">→</span>{CHECKS.map(check => { const family = datasetRecords.filter(record => checkGroup(record.expectation) === check); const failed = family.some(record => record.status === 'failed'); return <button key={check} onClick={() => family[0] && setSelected(family.find(record => record.status === 'failed') ?? family[0])} className={`rounded-md border px-3 py-2 text-xs ${failed ? 'border-red-500 bg-red-950/60 text-red-100' : family.length ? 'border-red-900 bg-[#341113] text-red-200' : 'border-[var(--color-border)] bg-[var(--color-surface-3)] text-[var(--color-text-muted)]'}`}>{check}{family.length ? ` · ${failed ? 'failed' : 'passed'}` : ' · N/A'}</button> })}</div> })}</div></ObservabilityCard>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><ObservabilityCard title="Failure analysis" description="Latest persisted expectation failures."><div className="space-y-3">{(selected ? [selected] : failures.slice(0, 5)).map(record => <button key={record.validationId} onClick={() => setSelected(record)} className="flex w-full items-center justify-between rounded-lg border border-red-950/60 bg-[#210f11] px-4 py-3 text-left"><div><p className="text-sm font-medium text-[var(--color-text-primary)]">{displayDataset(record.dataset)} · {record.expectation}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{formatNumber(record.unexpectedCount)} unexpected · {formatAbsoluteTime(record.timestamp)}</p></div><StatusBadge status="failed" /></button>)}{!selected && !failures.length && <p className="text-sm text-[var(--color-text-muted)]">No failed expectations in the retained history.</p>}</div>{selected && <div className="mt-4 rounded-lg border border-red-900/70 bg-red-950/20 p-4 text-sm"><p className="text-xs uppercase tracking-wider text-red-300">Selected failure</p><p className="mt-2">{(100 - selected.successPercent).toFixed(2)}% failure · {formatNumber(selected.unexpectedCount)} unexpected</p></div>}</ObservabilityCard><ObservabilityCard title="Validation execution timeline" description="Chronological GX runs with persisted duration and outcome."><div className="space-y-3">{runs.map(run => <div key={run.runId} className="flex gap-3"><div className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${run.failedCount === 0 ? 'bg-red-500' : 'bg-red-300 shadow-[0_0_10px_#ef4444]'}`} /><div className="min-w-0 flex-1 border-b border-red-950/40 pb-3"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm text-[var(--color-text-primary)]">{run.suiteName} · {run.datasource}</p><StatusBadge status={run.failedCount === 0 ? 'passed' : 'failed'} /></div><p className="mt-1 text-xs text-[var(--color-text-muted)]">{formatAbsoluteTime(run.timestamp)} · {run.expectationCount} checks · {run.durationMs == null ? 'duration unavailable' : `${(run.durationMs / 1000).toFixed(1)}s`}</p></div></div>)}{!runs.length && <p className="text-sm text-[var(--color-text-muted)]">No completed validation executions yet.</p>}</div></ObservabilityCard></div>
    <p className="sr-only">Outcome distribution: {distribution.map(item => `${item.name} ${item.value}`).join(', ')}</p>
  </main></div>
}
