services:

  airflow-init:
    image: apache/airflow:2.10.0
    container_name: airflow-init

    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - airflow_home:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.10.0
    container_name: airflow-webserver

    restart: unless-stopped

    depends_on:
      - airflow-init

    ports:
      - "8080:8080"

    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - airflow_home:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.0
    container_name: airflow-scheduler

    restart: unless-stopped

    depends_on:
      - airflow-init

    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - airflow_home:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data

    command: scheduler

volumes:
  airflow_home: