import { Link, useParams } from 'react-router-dom'
import { TopBar } from '@/components/layout/TopBar'
import { LoadingState } from '@/components/feedback/LoadingState'
import { ObservabilityCard, ObservabilityHero } from '@/features/observability/components'
import { useRevenueTrend } from '@/features/analytics/hooks/useRevenueTrend'
import { useTopCategories } from '@/features/analytics/hooks/useTopCategories'
import { useSellerPerformance } from '@/features/analytics/hooks/useSellerPerformance'
import { usePaymentDistribution } from '@/features/analytics/hooks/usePaymentDistribution'
import { formatCompactNumber, formatCurrency, formatNumber } from '@/lib/formatters'

type View = 'revenue' | 'categories' | 'sellers' | 'payments' | 'funnel' | 'geography'
const COPY: Record<View, [string, string, string]> = {
  revenue: ['Revenue Intelligence', 'Explain change through drivers, bridges, and concentration.', 'Why revenue changed'],
  categories: ['Category Intelligence', 'Identify dominant, emerging, and underperforming categories.', 'Which categories matter'],
  sellers: ['Seller Intelligence', 'Find the sellers and tiers creating durable value.', 'Who creates value'],
  payments: ['Payment Intelligence', 'Understand customer payment behavior and method mix.', 'How customers pay'],
  funnel: ['Customer Journey Intelligence', 'Locate conversion leakage throughout the customer journey.', 'Where customers are lost'],
  geography: ['Regional Intelligence', 'Compare state performance and regional opportunity.', 'Where regions perform'],
}
const WARM = ['#7F1D1D', '#DC2626', '#C2410C', '#D97706', '#FB7185']

export function AnalyticsDeepDivePage() {
  const { view: raw = 'revenue' } = useParams(); const view = (raw in COPY ? raw : 'revenue') as View
  const revenue = useRevenueTrend('month'); const categories = useTopCategories(10); const sellers = useSellerPerformance(10); const payments = usePaymentDistribution()
  const loading = revenue.isLoading || categories.isLoading || sellers.isLoading || payments.isLoading
  const props = { revenue: revenue.data?.points ?? [], geography: revenue.data?.geography ?? [], funnel: revenue.data?.funnel ?? [], categories: categories.data?.categories ?? [], sellers: sellers.data?.sellers ?? [], payments: payments.data?.methods ?? [] }
  return <div className="flex min-h-screen min-w-0 flex-col"><TopBar title={COPY[view][0]} description={COPY[view][2]} /><main className="flex-1 space-y-6 p-6 pb-6"><div className="text-xs text-[var(--color-text-muted)]"><Link to="/analytics" className="text-red-300 hover:text-red-100">Business Intelligence</Link> → {COPY[view][0]}</div><ObservabilityHero eyebrow="Specialized analytics" title={COPY[view][0]} description={COPY[view][1]} status={COPY[view][2]} />{loading ? <LoadingState variant="chart" /> : <Workspace view={view} {...props} />}</main></div>
}

function Workspace({ view, ...data }: { view: View; revenue: { period: string; revenue: number }[]; geography: { state: string; revenue: number; orders: number }[]; funnel: { stage: string; count: number }[]; categories: { category: string; revenue: number; unitsSold: number }[]; sellers: { sellerId: string; revenue: number; ordersFulfilled: number }[]; payments: { type: string; count: number; percentage: number }[] }) {
  if (view === 'geography') return <Geography data={data.geography} />
  if (view === 'revenue') return <Revenue data={data.revenue} categories={data.categories} />
  if (view === 'sellers') return <Sellers data={data.sellers} />
  if (view === 'categories') return <Categories data={data.categories} />
  if (view === 'payments') return <Payments data={data.payments} />
  return <Funnel data={data.funnel} />
}
function Geography({ data }: { data: { state: string; revenue: number; orders: number }[] }) { return <div className="space-y-6"><div className="grid grid-cols-1 gap-6 xl:grid-cols-[1fr_.8fr]"><Panel title="Brazil performance map" text="A geographic state cartogram; node scale represents revenue."><svg viewBox="0 0 360 300" className="mx-auto h-72 w-full max-w-md"><path d="M115 28 L235 48 300 105 265 230 180 278 85 220 50 125Z" fill="#2a1215" stroke="#9f2b2f" strokeWidth="3" />{data.map((d,i)=><g key={d.state}><circle cx={95+(i%4)*55} cy={80+Math.floor(i/4)*55} r={10+Math.min(18,d.revenue/100000)} fill={WARM[i%WARM.length]} opacity=".9"/><text x={95+(i%4)*55} y={84+Math.floor(i/4)*55} textAnchor="middle" fill="white" fontSize="9">{d.state}</text></g>)}</svg></Panel><Panel title="Regional performance matrix" text="Revenue and order volume by state."><Matrix rows={data.map(d=>[d.state,formatCurrency(d.revenue,true),formatCompactNumber(d.orders)])} heads={['State','Revenue','Orders']} /></Panel></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Panel title="Revenue density" text="Concentration is shown through regional intensity."><Density values={data.map(d=>d.revenue)} /></Panel><Panel title="Regional opportunity" text="High-order, lower-revenue states surface as opportunity."><Matrix rows={data.map(d=>[d.state,formatCompactNumber(d.orders),formatCurrency(d.revenue,true)])} heads={['State','Orders','Revenue']} /></Panel><Panel title="Top state comparison" text="A tabular decision view, not another chart."><Matrix rows={data.slice(0,6).map(d=>[d.state,formatCurrency(d.revenue,true),formatNumber(d.orders)])} heads={['State','Revenue','Orders']} /></Panel></div></div> }
function Revenue({ data, categories }: { data: { period:string;revenue:number }[]; categories:{category:string;revenue:number;unitsSold:number}[] }) { const base=data[0]?.revenue??0; return <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Panel title="Revenue waterfall" text="Period-over-period bridge of revenue movement."><Waterfall values={data.map(d=>d.revenue-base)} labels={data.map(d=>d.period)} /></Panel><Panel title="Revenue driver analysis" text="Category contribution to total revenue."><Density values={categories.map(d=>d.revenue)} labels={categories.map(d=>d.category)} /></Panel><Panel title="Revenue bridge" text="Positive and negative revenue deltas across periods."><Waterfall values={data.slice(1).map((d,i)=>d.revenue-data[i].revenue)} labels={data.slice(1).map(d=>d.period)} /></Panel><Panel title="Category contribution map" text="Category blocks scale by revenue contribution."><Blocks data={categories.map(d=>({label:d.category,value:d.revenue}))} /></Panel></div> }
function Sellers({ data }: { data:{sellerId:string;revenue:number;ordersFulfilled:number}[] }) { return <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Panel title="Seller performance matrix" text="Value compared with fulfillment volume."><Matrix rows={data.map(d=>[d.sellerId.slice(0,8),formatCurrency(d.revenue,true),formatNumber(d.ordersFulfilled)])} heads={['Seller','Revenue','Orders']} /></Panel><Panel title="Seller tier segmentation" text="Revenue tier bands."><Density values={data.map(d=>d.revenue)} /></Panel><Panel title="Seller leaderboard" text="Highest value producers."><Matrix rows={data.slice(0,8).map((d,i)=>[`#${i+1}`,d.sellerId.slice(0,10),formatCurrency(d.revenue,true)])} heads={['Rank','Seller','Revenue']} /></Panel></div> }
function Categories({ data }: { data:{category:string;revenue:number;unitsSold:number}[] }) { return <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Panel title="Category treemap" text="Block size shows category revenue."><Blocks data={data.map(d=>({label:d.category,value:d.revenue}))} /></Panel><Panel title="Category lifecycle" text="Revenue and unit velocity reveal lifecycle position."><Matrix rows={data.map(d=>[d.category,formatCurrency(d.revenue,true),formatNumber(d.unitsSold)])} heads={['Category','Revenue','Units']} /></Panel><Panel title="Revenue concentration curve" text="Cumulative contribution of leading categories."><Density values={data.map(d=>d.revenue)} /></Panel><Panel title="Category ranking table" text="Decision-ready category comparison."><Matrix rows={data.map((d,i)=>[`#${i+1}`,d.category,formatCurrency(d.revenue,true)])} heads={['Rank','Category','Revenue']} /></Panel></div> }
function Payments({ data }: { data:{type:string;count:number;percentage:number}[] }) { return <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Panel title="Payment flow" text="Customer payment methods flowing into completed value."><div className="flex flex-wrap items-center justify-center gap-3 pt-12">{data.map((d,i)=><><span key={d.type} className="rounded border border-red-900 bg-[#301114] px-3 py-2 text-xs">{d.type}</span>{i<data.length-1&&<span className="text-amber-500">→</span>}</>)}</div></Panel><Panel title="Payment composition" text="Method composition by share."><Blocks data={data.map(d=>({label:d.type,value:d.percentage}))} /></Panel><Panel title="Payment behavior segmentation" text="Observed volume and share per method."><Matrix rows={data.map(d=>[d.type,formatNumber(d.count),`${d.percentage}%`])} heads={['Method','Payments','Share']} /></Panel><Panel title="Payment risk distribution" text="Low-share methods are highlighted for review."><Density values={data.map(d=>d.percentage)} labels={data.map(d=>d.type)} /></Panel></div> }
function Funnel({ data }: { data:{stage:string;count:number}[] }) { return <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Panel title="Customer journey flow" text="Sankey-style progression through each journey stage."><div className="space-y-3 pt-4">{data.map((d,i)=><div key={d.stage}><div className="flex justify-between text-sm"><span>{d.stage}</span><span>{formatCompactNumber(d.count)}</span></div><div className="mt-1 h-7 bg-gradient-to-r from-[#7F1D1D] to-[#F97316]" style={{width:`${Math.max(24,100-i*16)}%`}} /></div>)}</div></Panel><Panel title="Stage leakage" text="Loss from one customer stage to the next."><Waterfall values={data.slice(1).map((d,i)=>d.count-data[i].count)} labels={data.slice(1).map(d=>d.stage)} /></Panel><Panel title="Cohort retention" text="Stage retention intensity grid."><Density values={data.map(d=>d.count)} /></Panel><Panel title="Drop-off explorer" text="Largest journey losses for investigation."><Matrix rows={data.slice(1).map((d,i)=>[d.stage,formatNumber(Math.max(0,data[i].count-d.count))])} heads={['Stage','Lost customers']} /></Panel></div> }
function Panel({ title,text,children }:{title:string;text:string;children:React.ReactNode}) { return <ObservabilityCard title={title} description={text}>{children}</ObservabilityCard> }
function Matrix({heads,rows}:{heads:string[];rows:string[][]}) { return <table className="w-full text-left text-xs"><thead className="text-[var(--color-text-muted)]"><tr>{heads.map(h=><th key={h} className="pb-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-red-950/40">{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className="py-2 text-[var(--color-text-secondary)]">{v}</td>)}</tr>)}</tbody></table> }
function Density({values,labels}:{values:number[];labels?:string[]}) { const max=Math.max(...values,1); return <div className="grid grid-cols-5 gap-2">{values.map((v,i)=><div key={i} className="rounded p-2 text-center text-[10px] text-white" style={{backgroundColor:WARM[Math.min(4,Math.floor((v/max)*4))]}}>{labels?.[i]??`${Math.round((v/max)*100)}%`}</div>)}</div> }
function Blocks({data}:{data:{label:string;value:number}[]}) { const max=Math.max(...data.map(d=>d.value),1); return <div className="flex min-h-52 flex-wrap gap-1">{data.map((d,i)=><div key={d.label} className="flex items-center justify-center rounded p-2 text-center text-xs text-white" style={{width:`${Math.max(22,(d.value/max)*100)}%`,height:`${60+(i%3)*35}px`,backgroundColor:WARM[i%WARM.length]}}>{d.label}</div>)}</div> }
function Waterfall({values,labels}:{values:number[];labels:string[]}) { const max=Math.max(...values.map(Math.abs),1); return <div className="flex h-52 items-end gap-2">{values.map((v,i)=><div key={labels[i]} className="flex flex-1 flex-col justify-end"><div className={v>=0?'bg-[#DC2626]':'bg-[#D97706]'} style={{height:`${Math.max(8,Math.abs(v)/max*160)}px`}} /><span className="mt-2 truncate text-[10px] text-[var(--color-text-muted)]">{labels[i]}</span></div>)}</div> }
