import { useMemo } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Tooltip, XAxis, YAxis } from 'recharts'
import { useQuery } from '@tanstack/react-query'
import { TopBar } from '@/components/layout/TopBar'
import { ChartContainer, chartTooltipStyle } from '@/components/charts/ChartContainer'
import { ErrorState } from '@/components/feedback/ErrorState'
import { LoadingState } from '@/components/feedback/LoadingState'
import { StatusBadge } from '@/components/ui/status-badge'
import { ObservabilityCard, ObservabilityHero, Metric } from '@/features/observability/components'
import { getSourceHistory, getSourceSummary } from '@/services/sourcesApi'
import { formatAbsoluteTime, formatCompactNumber, formatNumber } from '@/lib/formatters'

export function SourceMonitoringPage() {
  const summary = useQuery({ queryKey: ['sources', 'summary'], queryFn: getSourceSummary })
  const history = useQuery({ queryKey: ['sources', 'history'], queryFn: getSourceHistory })
  const sources = summary.data?.sources ?? []
  const loads = history.data?.loads ?? []
  const volume = useMemo(() => [...loads].reverse().map(load => ({ time: load.lastLoadTime ? new Date(load.lastLoadTime).toLocaleDateString() : 'Unknown', CSV: load.sourceType === 'CSV' ? load.recordsLoaded : 0, API: load.sourceType === 'REST API' ? load.recordsLoaded : 0 })), [loads])
  const healthy = sources.filter(source => source.status === 'healthy').length
  const failed = sources.length - healthy
  return <div className="flex min-h-screen min-w-0 flex-col"><TopBar title="Source Monitoring" description="Lineage, ingestion health, and source-load telemetry" /><main className="flex-1 space-y-6 p-6 pb-6">
    <ObservabilityHero eyebrow="Source observability" title="Trace every record from arrival to warehouse value." description="Monitor CSV and synthetic API loads through the medallion path." status={`${healthy}/${sources.length || 0} sources healthy`} />
    <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Healthy sources" value={`${healthy}/${sources.length}`} detail="Latest source observation" /><Metric label="Failed or delayed" value={failed} detail="Requires source-owner attention" /><Metric label="Records loaded" value={formatCompactNumber(sources.reduce((total, source) => total + source.recordsLoaded, 0))} detail="Latest reported source batches" /><Metric label="Load events" value={formatNumber(loads.length)} detail="Retained source audit history" /></section>
    {(summary.isLoading || history.isLoading) && <LoadingState variant="chart" />}{(summary.isError || history.isError) && <ErrorState onRetry={() => { summary.refetch(); history.refetch() }} />}
    <ObservabilityCard title="Source lineage flow" description="Observed volumes move from each source into the Bronze → Silver → Gold warehouse path."><div className="grid grid-cols-1 gap-5 xl:grid-cols-2">{sources.map(source => <div key={source.sourceName} className="rounded-lg border border-red-950/60 bg-[#180f10] p-4"><div className="flex items-center justify-between"><div><p className="font-medium text-[var(--color-text-primary)]">{source.sourceName}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{source.sourceType}</p></div><StatusBadge status={source.status === 'healthy' ? 'passed' : 'failed'} label={source.status} /></div><div className="mt-5 flex items-center gap-2 overflow-x-auto"><FlowNode label={source.sourceType === 'CSV' ? 'CSV' : 'API'} count={source.recordsLoaded} /><Arrow /><FlowNode label="Bronze" count={source.recordsLoaded} /><Arrow /><FlowNode label="Silver" count={null} /><Arrow /><FlowNode label="Gold" count={null} /></div><p className="mt-4 text-xs text-[var(--color-text-muted)]">Last load {source.lastLoadTime ? formatAbsoluteTime(source.lastLoadTime) : 'not yet observed'} · Batch {source.batchId ?? '—'}</p></div>)}</div></ObservabilityCard>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><ObservabilityCard title="Ingestion volume trend" description="Reported records loaded by source over time."><ChartContainer isEmpty={!volume.length}><AreaChart data={volume}><defs><linearGradient id="csvVolume" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#EF4444" stopOpacity={.45} /><stop offset="1" stopColor="#EF4444" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--color-border)" /><XAxis dataKey="time" tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip {...chartTooltipStyle} /><Area type="monotone" dataKey="CSV" stroke="#EF4444" fill="url(#csvVolume)" strokeWidth={2} /><Area type="monotone" dataKey="API" stroke="#F87171" fill="transparent" strokeWidth={2} /></AreaChart></ChartContainer></ObservabilityCard><ObservabilityCard title="Batch outcome history" description="Load volumes by source audit event; red status dots surface unhealthy executions."><ChartContainer isEmpty={!loads.length}><BarChart data={loads.slice(0, 14).reverse()}><CartesianGrid vertical={false} stroke="var(--color-border)" /><XAxis dataKey="sourceName" tickFormatter={value => String(value).replace(' Source', '')} tick={{ fill: 'var(--color-text-muted)', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip {...chartTooltipStyle} /><Bar dataKey="recordsLoaded" name="Records" fill="#991B1B" radius={[4, 4, 0, 0]} /></BarChart></ChartContainer></ObservabilityCard></div>
    <ObservabilityCard title="Source health stream" description="The most recent source batch executions and status signals."><div className="grid grid-cols-1 gap-3 lg:grid-cols-2">{loads.slice(0, 10).map((load, index) => <div key={`${load.sourceName}-${index}`} className="flex items-center justify-between rounded-lg border border-red-950/40 bg-[#180f10] px-4 py-3"><div><p className="text-sm font-medium text-[var(--color-text-primary)]">{load.sourceName}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{formatNumber(load.recordsLoaded)} records · {load.lastLoadTime ? formatAbsoluteTime(load.lastLoadTime) : 'unknown time'}</p></div><StatusBadge status={load.status === 'healthy' ? 'passed' : 'failed'} label={load.status} /></div>)}</div></ObservabilityCard>
  </main></div>
}

function Arrow() { return <span className="shrink-0 text-red-500">→</span> }
function FlowNode({ label, count }: { label: string; count: number | null }) { return <div className="min-w-20 rounded-md border border-red-900/70 bg-gradient-to-br from-[#4a1214] to-[#220e10] px-3 py-2 text-center"><p className="text-xs font-medium text-red-100">{label}</p><p className="mt-1 text-xs tabular-nums text-red-300">{count === null ? '—' : formatCompactNumber(count)}</p></div> }
